/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.integra.utils;

import java.util.HashMap;

/**
 *
 * @author Vidya
 */
public class ErrorList {

    public static HashMap<String, String> getErrorMap() {
        HashMap<String, String> errorMap = new HashMap<String, String>();
        errorMap.put("ASP-801", "Internal server error. Kindly contact ASP for more details");
        errorMap.put("ASP-802", "Internal server error. Kindly contact ASP for more details");
        errorMap.put("ASP-803", "Invalid Request sent from ASP to ESP");
        errorMap.put("ASP-804", "Internal server error. Kindly contact ASP for more details");
        errorMap.put("ASP-805", "Invalid response received from kua.kindly contact ASP for more details");
        errorMap.put("ASP-806", "Unable to connect with e-Sign server. Kindly contact ASP for more details");
        errorMap.put("ASP-807", "Problem in generating certificate");
        errorMap.put("ASP-808", "Error in parsing response");
        errorMap.put("ASP-809", "Transaction id verification failed");
        errorMap.put("ASP-810", "There is some problem at ESP.Kindly contact ASP for more details");
        errorMap.put("ASP-811", "Not used");
        errorMap.put("ASP-812", "Invalid value of version");
        errorMap.put("ASP-813", "Invalid Value of Sc");
        errorMap.put("ASP-814", "Aadhaar number not present");
        errorMap.put("ASP-815", "Signature value not present in ASP Request");
        errorMap.put("ASP-816", "There is some problem at Aadhaar otp service. Kindly contact ASP for more details @ESP");
        errorMap.put("ASP-817", "There is some problem at e-KYC. Kindly contact ASP for more details");
        errorMap.put("ASP-818", "No ASP XML Digital Signature Found, request is discarded");
        errorMap.put("ASP-819", "Not used");
        errorMap.put("ASP-820", "Invalid response received from esignserver.kindly contact ASP for more details");
        errorMap.put("ASP-821", "Invalid transaction id received from kua");
        errorMap.put("ASP-822", "Invalid transaction id received from eSignserver");
        errorMap.put("ASP-823", "Invalid Aadhaar number");
        errorMap.put("ASP-824", "Invalid transaction id sent to ESP");
        errorMap.put("ASP-825", "Invalid asp-id sent to ESP");
        errorMap.put("ASP-827", "Could not parse the ASP XML Digital Signature at ESP, request is discarded");
        errorMap.put("ASP-828", "ASP XML Digital Signature validation failed, request is discarded");
        errorMap.put("ASP-829", "Input value is invalid.");
        errorMap.put("ASP-901", "Invalid E-Sign Class");
        errorMap.put("ASP-902", "Invalid ASP ID. It cannot be Empty");
        errorMap.put("ASP-903", "Invalid ASP ID. It may not exist or may be inactive");
        errorMap.put("ASP-905", "Document Hash not received from ASP");
        errorMap.put("ASP-906", "Aadhaar cannot be Empty");
        errorMap.put("ASP-907", "Request Time Stamp cannot be Empty");
        errorMap.put("ASP-908", "Request Time Stamp is not valid. Please check the server time");
        errorMap.put("ASP-909", "Transaction Id cannot be Empty");
        errorMap.put("ASP-910", "Duplicate Transaction Id sent by ASP");
        errorMap.put("ASP-911", "ASP Input XML Signature verification failed");
        errorMap.put("ASP-922", "Invalid Signature on ASP Input XML. Please use the corresponding certificate mapped with ESP");
        errorMap.put("ASP-991", "ESP Database Connectivity Error");
        errorMap.put("ASP-992", "ASP Input XML Parsing Error");
        errorMap.put("ASP-993", "Error Parsing CA Response XML @ESP");
        errorMap.put("ASP-994", "Error from KSA Server");
        errorMap.put("ASP-995", "Unknown CIDR Error");
        errorMap.put("ASP-996", "Invalid eKYC response/Unable to parse UidData XML string @ESP");
        errorMap.put("ASP-999", "Unknown Error @ESP");

        errorMap.put("K-100", "Resident authentication failed @CIDR-KUA");
        errorMap.put("K-200", "Resident data currently not available @CIDR-KUA");
        errorMap.put("K-540", "Invalid KYC XML @CIDR-KUA");
        errorMap.put("K-541", "Invalid e-KYC API version @CIDR-KUA");
        errorMap.put("K-542", "Invalid resident consent (\"rc\" attribute in \"Kyc\" element) @CIDR-KUA");
        errorMap.put("K-543", "Invalid timestamp (\"ts\" attribute in \"Kyc\" element) @CIDR-KUA");
        errorMap.put("K-544", "Invalid resident auth type (\"ra\" attribute in \"Kyc\" element does not match what is in PID block) @CIDR-KUA");
        errorMap.put("K-545", "Resident has opted-out of this service @CIDR-KUA");
        errorMap.put("K-550", "Invalid Uses Attribute @CIDR-KUA");
        errorMap.put("K-551", "Invalid \"Txn\" namespace @CIDR-KUA");
        errorMap.put("K-552", "Invalid License key @CIDR-KUA");
        errorMap.put("K-569", "Digital signature verification failed for e-KYC XML @CIDR-KUA");
        errorMap.put("K-570", "Invalid key info in digital signature for e-KYC XML (it is either expired,or does not belong to the AUA or is not created by a well-known Certification Authority) @CIDR-KUA");
        errorMap.put("K-600", "AUA is invalid or not an authorized KUA @CIDR-KUA");
        errorMap.put("K-601", "ASA is invalid or not an authorized KSA @CIDR-KUA");
        errorMap.put("K-602", "KUA encryption key not available @CIDR-KUA");
        errorMap.put("K-603", "KSA encryption key not available @CIDR-KUA");
        errorMap.put("K-604", "KSA Signature not allowed @CIDR-KUA");
        errorMap.put("K-605", "Neither KUA key nor KSA encryption key are available @CIDR-KUA");
        errorMap.put("K-955", "Technical Failure @CIDR-KUA");
        errorMap.put("K-999", "Unknown Error @CIDR-KUA");

        errorMap.put("100", "\"Pi\" (basic) attributes of demographic data did not match.  @CIDR-AUA");
        errorMap.put("200", "\"Pa\" (address) attributes of demographic data did not match  @CIDR-AUA");
        errorMap.put("300", "Biometric data did not match  @CIDR-AUA");
        errorMap.put("310", "Duplicate fingers used  @CIDR-AUA");
        errorMap.put("311", "Duplicate Irises used.  @CIDR-AUA");
        errorMap.put("312", "FMR and FIR cannot be used in same transaction  @CIDR-AUA");
        errorMap.put("313", "Single FIR record contains more than one finger  @CIDR-AUA");
        errorMap.put("314", "Number of FMR/FIR should not exceed 10  @CIDR-AUA");
        errorMap.put("315", "Number of IIR should not exceed 2  @CIDR-AUA");
        errorMap.put("400", "Invalid OTP value  @CIDR-AUA");
        errorMap.put("401", "Invalid TKN value  @CIDR-AUA");
        errorMap.put("500", "Invalid encryption of Skey  @CIDR-AUA");
        errorMap.put("501", "Invalid certificate identifier in \"ci\" attribute of \"Skey\"  @CIDR-AUA");
        errorMap.put("502", "Invalid encryption of Pid  @CIDR-AUA");
        errorMap.put("503", "Invalid encryption of Hmac  @CIDR-AUA");
        errorMap.put("504", "Session key re-initiation required due to expiry or key out of sync  @CIDR-AUA");
        errorMap.put("505", "Synchronized Key usage not allowed for the AUA  @CIDR-AUA");
        errorMap.put("510", "Invalid Auth XML format  @CIDR-AUA");
        errorMap.put("511", "Invalid PID XML format  @CIDR-AUA");
        errorMap.put("520", "Invalid device  @CIDR-AUA");
        errorMap.put("521", "Invalid FDC code under Meta tag  @CIDR-AUA");
        errorMap.put("522", "Invalid IDC code under Meta tag  @CIDR-AUA");
        errorMap.put("530", "Invalid authenticator code  @CIDR-AUA");
        errorMap.put("540", "Invalid Auth XML version  @CIDR-AUA");
        errorMap.put("541", "Invalid PID XML version  @CIDR-AUA");
        errorMap.put("542", "AUA not authorized for ASA. This error will be returned if AUA and ASA do not have linking in the portal  @CIDR-AUA");
        errorMap.put("543", "Sub-AUA not associated with \"AUA\". This error will be returned if Sub-AUA specified in \"sa\" attribute is not added as \"Sub-AUA\" in portal  @CIDR-AUA");
        errorMap.put("550", "Invalid \"Uses\" element attributes  @CIDR-AUA");
        errorMap.put("551", "Invalid \"tid\" value for registered device  @CIDR-AUA");
        errorMap.put("552", "Invalid registered device key, please reset  @CIDR-AUA");
        errorMap.put("553", "Invalid registered device HOTP, please reset  @CIDR-AUA");
        errorMap.put("554", "Invalid registered device encryption  @CIDR-AUA");
        errorMap.put("555", "Mandatory reset required for registered device  @CIDR-AUA");
        errorMap.put("561", "Request expired (\"Pid->ts\" value is older than N hours where N is a configured threshold in authentication server)  @CIDR-AUA");
        errorMap.put("562", "Timestamp value is future time (value specified \"Pid->ts\" is ahead of authentication server time beyond acceptable threshold)  @CIDR-AUA");
        errorMap.put("563", "Duplicate request (this error occurs when exactly same authentication request was re-sent by AUA)  @CIDR-AUA");
        errorMap.put("564", "HMAC Validation failed  @CIDR-AUA");
        errorMap.put("565", "AUA license has expired  @CIDR-AUA");
        errorMap.put("566", "Invalid non-decryptable license key  @CIDR-AUA");
        errorMap.put("567", "Invalid input (this error occurs when some unsupported characters were found in Indian language values, \"lname\" or \"lav\")  @CIDR-AUA");
        errorMap.put("568", "Unsupported Language  @CIDR-AUA");
        errorMap.put("569", "Digital signature verification failed (means that authentication request XML was modified after it was signed)  @CIDR-AUA");
        errorMap.put("570", "Invalid key info in digital signature (this means that certificate used for signing the authentication request is not valid – it is either expired, or does not belong to the AUA or is not created by a well-known Certification Authority)  @CIDR-AUA");
        errorMap.put("571", "PIN Requires reset (this error will be returned if resident is using the default PIN which needs to be reset before usage)  @CIDR-AUA");
        errorMap.put("572", "Invalid biometric position  @CIDR-AUA");
        errorMap.put("573", "Pi usage not allowed as per license  @CIDR-AUA");
        errorMap.put("574", "a usage not allowed as per license  @CIDR-AUA");
        errorMap.put("575", "fa usage not allowed as per license  @CIDR-AUA");
        errorMap.put("576", "FMR usage not allowed as per license  @CIDR-AUA");
        errorMap.put("577", "FIR usage not allowed as per license  @CIDR-AUA");
        errorMap.put("578", "IIR usage not allowed as per license  @CIDR-AUA");
        errorMap.put("579", "OTP usage not allowed as per license  @CIDR-AUA");
        errorMap.put("580", "PIN usage not allowed as per license  @CIDR-AUA");
        errorMap.put("581", "Fuzzy matching usage not allowed as per license  @CIDR-AUA");
        errorMap.put("582", "Local language usage not allowed as per license  @CIDR-AUA");
        errorMap.put("584", "Invalid pincode in LOV attribute under Meta tag  @CIDR-AUA");
        errorMap.put("585", "Invalid geo-code in LOV attribute under Meta tag  @CIDR-AUA");
        errorMap.put("710", "Missing \"Pi\" data as specified in \"Uses\"  @CIDR-AUA");
        errorMap.put("720", "Missing \"Pa\" data as specified in \"Uses\"  @CIDR-AUA");
        errorMap.put("721", "Missing \"Pfa\" data as specified in \"Uses\"  @CIDR-AUA");
        errorMap.put("730", "Missing PIN data as specified in \"Uses\"  @CIDR-AUA");
        errorMap.put("740", "Missing OTP data as specified in \"Uses\"  @CIDR-AUA");
        errorMap.put("800", "Invalid biometric data  @CIDR-AUA");
        errorMap.put("810", "Missing biometric data as specified in \"Uses\"  @CIDR-AUA");
        errorMap.put("811", "Missing biometric data in CIDR for the given Aadhaar number  @CIDR-AUA");
        errorMap.put("812", "Resident has not done \"Best Finger Detection\". Application should initiate BFD application to help resident identify their best fingers. See Aadhaar Best Finger Detection API specification.  @CIDR-AUA");
        errorMap.put("820", "Missing or empty value for \"bt\" attribute in \"Uses\" element  @CIDR-AUA");
        errorMap.put("821", "Invalid value in the \"bt\" attribute of \"Uses\" element  @CIDR-AUA");
        errorMap.put("901", "No authentication data found in the request (this corresponds to a scenario wherein none of the auth data – Demo, Pv, or Bios – is present)  @CIDR-AUA");
        errorMap.put("902", "Invalid \"dob\" value in the \"Pi\" element (this corresponds to a scenarios wherein \"dob\" attribute is not of the format \"YYYY\" or \"YYYY-MM-DD\", or the age of resident is not in valid range)  @CIDR-AUA");
        errorMap.put("910", "Invalid \"mv\" value in the \"Pi\" element  @CIDR-AUA");
        errorMap.put("911", "Invalid \"mv\" value in the \"Pfa\" element  @CIDR-AUA");
        errorMap.put("912", "Invalid \"ms\" value  @CIDR-AUA");
        errorMap.put("913", "Both \"Pa\" and \"Pfa\" are present in the authentication request (Pa and Pfa are mutually exclusive)  @CIDR-AUA");
        errorMap.put("940", "Unauthorized ASA channel  @CIDR-AUA");
        errorMap.put("941", "Unspecified ASA channel  @CIDR-AUA");
        errorMap.put("980", "Unsupported option  @CIDR-AUA");
        errorMap.put("997", "Invalid Aadhaar status (Aadhaar is not in authenticatable status)  @CIDR-AUA");
        errorMap.put("998", "Invalid Aadhaar Number  @CIDR-AUA");
        errorMap.put("999", "Unknown error CIDR-AUA");
        
        errorMap.put("ESS101", "Internal Error @ESP");
        errorMap.put("ESS102", "Error connecting HSM @ESP");
        errorMap.put("ESS103", "Database Connectivity Error @ESP");
        errorMap.put("ESS104", "Error parsing ESign Request xml @ESP");
        errorMap.put("ESS105", "Empty Transaction ID @ESP");
        errorMap.put("ESS106", "Invalid Transaction ID @ESP");
        errorMap.put("ESS107", "Duplicate Transaction ID @ESP");
        errorMap.put("ESS108", "Invalid timestamp @ESP");
        errorMap.put("ESS109", "Invalid version @ESP");
        errorMap.put("ESS110", "Empty Input doc hash @ESP");
        errorMap.put("ESS111", "Invalid Input doc hash @ESP");
        errorMap.put("ESS112", "Empty Common Name @ESP");
        errorMap.put("ESS113", "Invalid UID @ESP");
        errorMap.put("ESS114", "Empty pseudonym @ESP");
        errorMap.put("ESS115", "Empty FormC @ESP");
        errorMap.put("ESS116", "FormC Base64 Decoding Fail @ESP");
        errorMap.put("ESS117", "FormC Signature Verification Fail @ESP");
        errorMap.put("ESS118", "Error generating key pair @ESP");
        errorMap.put("ESS119", "Error generating Certificate Request @ESP");
        errorMap.put("ESS120", "Error signing digestInfo @ESP");
        errorMap.put("ESS121", "Error generating ca request xml @ESP");
        errorMap.put("ESS122", "Error signing CertReq xml @ESP");
        errorMap.put("ESS123", "CA connection fail @ESP");
        errorMap.put("ESS124", "Error parsing CA response XML @ESP");
        errorMap.put("ESS125", "Invalid timestamp from CA response @ESP");
        errorMap.put("ESS126", "Invalid transaction ID from CA response @ESP");
        errorMap.put("ESS127", "DSC can not be empty in Ca response @ESP");
        errorMap.put("ESS128", "Error generating PKCS7 Response @ESP");
        errorMap.put("ESS129", "Error generating eSign Response xml @ESP");
        errorMap.put("ESS130", "Error in memory allocation @ESP");
        errorMap.put("CA01", "CSR Data cannot be empty @ESP");
        errorMap.put("CA02", "Txn cannot be empty @ESP");
        errorMap.put("CA03", "Time stamp cannot be empty @ESP");
        errorMap.put("CA04", "ver cannot be empty @ESP");
        errorMap.put("CA06", "Unknown Error @ESP");
        errorMap.put("CA07", "Invalid Time stamp @ESP");
        errorMap.put("CA08", "Error in generating DSC @ESP");
        errorMap.put("CA09", "Error in connection to HSM @ESP");
        errorMap.put("CA10", "Duplicate TXN ID @ESP");
        errorMap.put("CA11", "Invalid Version @ESP");
        errorMap.put("CA12", "Invalid TXN ID @ESP");
        errorMap.put("CA13", "Invalid CSR @ESP");
        errorMap.put("CA14", "CSR verification failed @ESP");
        errorMap.put("OT01", "Xml is invalid @ASA");
        errorMap.put("OT02", "Code invalid @ASA");
        errorMap.put("OT03", "Internal server error (Data Base) @ASA");
        errorMap.put("OT04", "MPLS connectivity failed CDAC to UID @ASA");
        errorMap.put("OT05", "No response from UID @ASA");
        errorMap.put("OT10", "Unknown error @ASA");
        errorMap.put("OT11", "Xml is invalid @AUA");
        errorMap.put("OT12", "Sub aua code invalid @AUA");
        errorMap.put("OT13", "Internal server error ( Signature Problem) @AUA");
        errorMap.put("OT14", "Internal server error (AUA to ASA connectivity failed) @AUA");
        errorMap.put("OT15", "License key invalid @AUA");
        errorMap.put("OT16", "Internal server error (Data Base ) @AUA");
        errorMap.put("OT17", "Internal server error (Response error) @AUA");
        errorMap.put("OT99", "Unknown error @AUA");
        errorMap.put("KS01", "Xml invalid @KSA");
        errorMap.put("KS02", "Code invalid @KSA");
        errorMap.put("KS03", "Internal server error (Data Base) @KSA");
        errorMap.put("KS04", "MPLS connectivity failed CDAC to UID @KSA");
        errorMap.put("KS05", "No response from UID @KSA");
        errorMap.put("KS10", "Unknown error @KSA");
        errorMap.put("KS11", "Xml invalid @KUA");
        errorMap.put("KS12", "Sub aua code invalid @KUA");
        errorMap.put("KS13", "Internal server error (Data base) @KUA");
        errorMap.put("KS14", "Internal error (Signature error) @KUA");
        errorMap.put("KS15", "Internal server error (KUA to KSA connectivity failed) @KUA");
        errorMap.put("KS16", "license key invalid @KUA");
        errorMap.put("KS17", "Kyc Decryption error @KUA");
        errorMap.put("KS18", "Internal server error (Response error) @KUA");
        errorMap.put("KS99", "Unknown Error @KUA");
        return errorMap;
    }
}
